# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Ejecucion_Test:

    runs-on: ubuntu-latest

    steps:
    - name: Obtener-Codigo
      uses: actions/checkout@v4
    - name: COnfigurar-Node(V22)
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Instalar-Dependencias
      run: npm ci
    - name: Ejecutar-Lint
      run: npm run lint
    - name: Compilar
      run: npm run build --if-present
    - name: Ejecutar-Tests
      run: npm test
